### ISSUE TITLE
[BUG] AUR install fails

### ISSUE THREAD

**Issue by slippuu** [hyprland-community/hyprland-autoname-workspaces#115]
**Describe the bug**
When installing via `yay -S hyprland-autoname-workspaces-git`, console shows:

```
failures:

---- renamer::formatter::tests::test_app_workspace_new stdout ----
thread 'renamer::formatter::tests::test_app_workspace_new' panicked at src/renamer/formatter.rs:214:9:
assertion `left == right` failed
  left: None
 right: Fullscreen
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

---- renamer::tests::test_app_client_partial_eq stdout ----
thread 'renamer::tests::test_app_client_partial_eq' panicked at src/renamer/mod.rs:378:9:
assertion `left == right` failed
  left: true
 right: false


failures:
    renamer::formatter::tests::test_app_workspace_new
    renamer::tests::test_app_client_partial_eq

test result: FAILED. 24 passed; 2 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.03s

error: test failed, to rerun pass `--bin hyprland-autoname-workspaces`
make: *** [Makefile:25: test] Error 101
==> ERROR: A failure occurred in check().
    Aborting...
 -> error making: hyprland-autoname-workspaces-git-exit status 4
 -> Failed to install the following packages. Manual intervention is required:
hyprland-autoname-workspaces-git - exit status 4
```

**Program version?**

- N/A

**Program configuration dump? (ideally)**

- N/A

**To Reproduce**
`yay -S hyprland-autoname-workspaces-git`

**Expected behavior**
Install to be successful

**Linux Distro (please complete the following information):**

- Arch Linux (Kernel: 6.10.10-arch1-1)

**Comment by chris2052** [comment]
Same here...

**Comment by matt-fff** [comment]
This should be corrected now that https://github.com/hyprland-community/hyprland-autoname-workspaces/pull/120 is merged. I've tested on my EndeavorOS box and it seemed to work. Please let me know.

**Comment by matt-fff** [comment]
I'm going to close for the time being, but we can re-open if this is still an issue.
